#!/bin/bash
scope=""
bang=""
while [[ $# -gt 0 ]]; do
  case "$1" in
    -s) scope="($2)"; shift 2 ;;
    -w) bang="!"; shift 1 ;;
    *) break ;;
  esac
done

if [ -z "$1" ]; then
  git commit -m "chore${scope}${bang}: " -e
else
  git commit -m "chore${scope}${bang}: ${*}"
fi
